# Generated by Django 5.0.2 on 2024-04-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
